# Generated by Django 5.2.5 on 2025-09-14 23:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
