# Generated by Django 5.2.5 on 2025-08-19 07:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='A short summary for previews')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Main article body (rich-text editor with image upload support)')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_images', models.ManyToManyField(blank=True, help_text='Additional inline images for the article', related_name='posts', to='blog.blogimage')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
