# Generated by Django 5.2.5 on 2025-08-21 17:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.CharField(choices=[('3_star', '3 Star'), ('4_star', '4 Star'), ('5_star', '5 Star')], default='3_star', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='mode_of_travel',
            field=models.CharField(choices=[('flight', 'Flight'), ('road', 'Road'), ('rail', 'Rail'), ('cruise', 'Cruise')], default='flight', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
