# Generated by Django 5.2.5 on 2025-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_duration_booking_end_date_booking_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='If you selected Special Package, tell us what you’d like included.'),
        ),
    ]
