# Generated by Django 5.2.5 on 2025-08-18 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='wishlisted_by',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
