# Generated by Django 5.2.5 on 2025-08-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_wishlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
