# Generated by Django 5.2.5 on 2025-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Mark as hot trip to feature on home page'),
        ),
    ]
