# Generated by Django 5.2.5 on 2025-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_safari',
            field=models.BooleanField(default=False, help_text='Mark this category as Safari type'),
        ),
    ]
