# Generated by Django 5.2.5 on 2025-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_category_is_safari'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='excluded',
            field=models.TextField(blank=True, help_text='Enter one item per line for things NOT included in this package'),
        ),
        migrations.AddField(
            model_name='package',
            name='included',
            field=models.TextField(blank=True, help_text='Enter one item per line for things included in this package'),
        ),
    ]
