# Generated by Django 5.2.5 on 2025-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_tripimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
